module.exports = {
	players : [
	{name : "Ronaldo", pic: "http://3.bp.blogspot.com/-PFoIOew-0w0/UPhcobqnEzI/AAAAAAAAATY/sa_wQxV7LDU/s1600/cristiano-ronaldo-uefa.jpg", handle : "", cost : 50, id : 1, sname : "ronaldo"},
	{name : "Messi", pic: "http://bamada.net/wp-content/uploads/2013/06/LIONEL-MESSI-BLLON-OR-SENEGAL-DAKAR-ABIDJAN-BLACK.jpg", handle : "", cost : 40, id : 2, sname : "messi"},
	{name : "Rooney", pic: "http://images4.wikia.nocookie.net/__cb20130520211420/football/en/images/0/01/63891.jpg", handle : "", cost : 40, id : 3, sname : "rooney"},
	{name : "Ramsey", pic: "http://totalfootballmadness.com/wp-content/uploads/2011/03/Aaron-Ramsey-2.jpg", handle : "aaronramsey", cost : 20, id : 4, sname : "ramsey"},
	{name : "Ribery", pic: "http://cdn.24.co.za/files/Cms/General/d/2571/1a07348cb48c439385beeda10d2d86df.jpg", handle : "", cost : 10, id : 5, sname : "ribery"},
	{name : "Januzaj", pic: "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc3/s160x160/1390469_218944621606532_2068683860_a.jpg", handle : "", cost : 10, id : 6, sname : "januzaj"},
    {name : "Ozil", pic: "http://images.supersport.com/2013/10/Mesut-Ozil-130911-Practice-Arsenal-300.jpg", handle : "", cost : 20, id: 7, sname: "ozil"},
    {name : "Neymar", pic: "http://thenet.ng/wp-content/uploads/2013/03/Neymar1-200x200.jpg", handle : "", cost : 20, id: 8, sname: "neymar"},
    {name : "Bale", pic: "http://img.uefa.com/imgml/TP/players/14/2013/324x324/102225.jpg", handle : "", cost : 10, id: 9, sname: "gareth bale"},
    {name : "Barton", pic: "http://www.footballgeeza.com/wp-content/uploads/2012/06/JOEY-BARTON-1-160x160.png", handle : "", cost : 30, id: 10, sname: "barton"},
    {name : "Ferdinand", pic: "http://www.eadt.co.uk/polopoly_fs/soccer_england_225057_1_1378771!image/1791587933.jpg_gen/derivatives/landscape_630/1791587933.jpg", handle : "", cost : 30, id: 11, sname: "rio ferdinand"},
    {name : "Carrick", pic: "http://img.uefa.com/imgml/TP/players/14/2012/324x324/50909.jpg", handle : "", cost : 20, id: 12, sname: "carrick"},
    {name : "Fabregas", pic: "http://ball72.com/data_images/cesc-fabregas/cesc-fabregas-01.jpg", handle : "", cost : 30, id: 13, sname: "fabregas"},
    {name : "Lampard", pic: "http://cdn.staticneo.com/w/fifa/thumb/3/36/Frank_Lampard.jpg/250px-Frank_Lampard.jpg", handle : "", cost : 10, id: 14, sname: "lampard"},
    {name : "Suarez", pic: "http://images.footballfancast.com/players/300px/liverpool/Luis-Suarez.jpg", handle : "luis16suarez", cost : 20, id: 15, sname: "suarez"},
    {name : "Toure", pic:"http://static9.therichestimages.com/cdn/300/300/70/t/wp-content/uploads/2011/05/Yaya_Tour%C3%A9.jpg", handle: "Toure_yaya42", cost : 20, id: 16, sname: "yaya toure"},
    {name : "Nani", pic:"http://www.unlulernereli.com/wp-content/uploads/2013/05/nani.jpg", handle : "luisnani", cost : 30, id: 17, sname: "nani"},
    {name : "Balotelli", pic:"http://img.thesun.co.uk/aidemitlum/archive/01698/mariobalotelli1_1698070a.jpg", handle : "FinallyMario", cost : 20, id: 18, sname: "balotelli"},
    {name : "van Persie", pic:"http://sim02.in.com/bff83ab25e6fb61153257631fe578c11_m.jpg", handle : "Persie_Official", cost : 30, id: 19, sname: "van persie"},
    {name : "Nasri", pic:"http://totalfootballmadness.com/wp-content/uploads/2010/12/Samir-Nasri-2.jpg", handle : "SamNasri19", cost : 20, id: 20, sname: "nasri"},
    {name : "Lewandowski", pic:"https://lh4.googleusercontent.com/-d-QiHx41wno/Ug4EDNJeQZI/AAAAAAAAC-s/3Xdd0uq9oiU/s300-no/Robert-Lewandowski-Borussia+Dortmund.jpg", handle : "", cost : 20, id: 21, sname: "lewandowski"},
    {name : "Giroud", pic:"http://www.topnews.in/sports/files/Olivier-Giroud-1.jpg", handle : "_OlivierGiroud_", cost : 30, id: 22, sname: "giroud"},
    {name : "Ibrahimovic", pic:"http://melosport.files.wordpress.com/2013/04/zlatan-ibrahimovic.jpg", handle : "Ibra_official", cost : 20, id: 23, sname: "zlatan"},
    {name : "Luiz", pic:"https://lh6.googleusercontent.com/-gSgjLQl0qYA/AAAAAAAAAAI/AAAAAAAAAyo/c_s0lZNUIuI/photo.jpg", handle : "DavidLuiz_4", cost : 20, id: 24, sname: "luiz"},
    {name : "Aguero", pic:"http://img.fannation.com/upload/truth_rumor/photo_upload/326/610/full/aguero_city.jpg", handle : "aguerosergiokun", cost : 30, id: 25, sname: "aguero"},
    {name : "Kompany", pic:"http://totalfootballmadness.com/wp-content/uploads/2012/04/Vincent-Kompany-1.jpg", handle : "VincentKompany", cost : 10, id: 26, sname: "kompany"},
    {name : "Pique", pic:"http://images.supersport.com/Gerard-Pique-celebrates25102010AI300.jpg", handle : "3gerardpique", cost : 30, id: 27, sname: "pique"},
    {name : "Hazard", pic:"http://img.skysports.com/13/05/247x247/Eden-Hazard-Chelsea-Europa-League_2944692.jpg", handle : "hazardeden10", cost : 20, id: 28, sname: "hazard"},
    {name : "Gotze", pic:"https://pbs.twimg.com/profile_images/378800000384811522/67c7ced6a8ebc0ce57fbbc2f9bc8e555.jpeg", handle : "MarioGoetze", cost : 10, id: 29, sname: "gotze"},
    {name : "Falcao", pic:"http://www.correodelorinoco.gob.ve/wp-content/uploads/2013/10/Radamel-Falcao.jpg", handle : "FALCAO", cost : 20, id: 30, sname: "falcao"},
    {name : "Juan Mata", pic:"http://theoriginalwinger.com/wp-content/uploads/2014/01/Juan-Mata.jpg", handle : "juanmata8", cost : 20, id: 31, sname: "juan mata"},
    {name : "Kagawa", pic:"https://pbs.twimg.com/profile_images/2550070556/C7H5IIp4", handle : "evilkagawa", cost : 40, id: 32, sname: "kagawa"},
    {name : "Torres", pic:"http://i53.tinypic.com/sg4lzt.jpg", handle : "Torres", cost : 10, id: 33, sname: "torres"}
    /*{name : "", pic:"", handle : "", cost : 0, id: 34, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 35, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 36, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 37, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 38, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 39, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 40, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 41, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 42, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 43, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 44, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 45, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 46, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 47, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 48, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 49, sname: ""},
    {name : "", pic:"", handle : "", cost : 0, id: 50, sname: ""},*/

	]
};

//{name : "", pic:"", handle : "", cost : 0, id: , sname: ""},
